// !! This file is generated by an NPM script. !!

declare namespace tfm {
  namespace $enum {
    export namespace bonus {
      export const point = 0;
      export const speed = 1;
      export const death = 2;
      export const spring = 3;
      export const booster = 5;
      export const electricArc = 6;
    }
    export namespace emote {
      export const dance = 0;
      export const laugh = 1;
      export const cry = 2;
      export const kiss = 3;
      export const angry = 4;
      export const clap = 5;
      export const sleep = 6;
      export const facepaw = 7;
      export const sit = 8;
      export const confetti = 9;
      export const flag = 10;
      export const marshmallow = 11;
      export const selfie = 12;
      export const highfive = 13;
      export const partyhorn = 16;
      export const hug = 17;
      export const jigglypuff = 20;
      export const kissing = 21;
      export const carnaval = 24;
      export const rockpaperscissors = 25;
    }
    export namespace ground {
      export const wood = 0;
      export const ice = 1;
      export const trampoline = 2;
      export const lava = 3;
      export const chocolate = 4;
      export const earth = 5;
      export const grass = 6;
      export const sand = 7;
      export const cloud = 8;
      export const water = 9;
      export const stone = 10;
      export const snow = 11;
      export const rectangle = 12;
      export const circle = 13;
      export const invisible = 14;
      export const web = 15;
      export const yellowGrass = 17;
      export const pinkGrass = 18;
      export const acid = 19;
    }
    export namespace particle {
      export const whiteGlitter = 0;
      export const blueGlitter = 1;
      export const orangeGlitter = 2;
      export const cloud = 3;
      export const dullWhiteGlitter = 4;
      export const heart = 5;
      export const bubble = 6;
      export const tealGlitter = 9;
      export const spirit = 10;
      export const yellowGlitter = 11;
      export const ghostSpirit = 12;
      export const redGlitter = 13;
      export const waterBubble = 14;
      export const plus1 = 15;
      export const plus10 = 16;
      export const plus12 = 17;
      export const plus14 = 18;
      export const plus16 = 19;
      export const meep = 20;
      export const redConfetti = 21;
      export const greenConfetti = 22;
      export const blueConfetti = 23;
      export const yellowConfetti = 24;
      export const diagonalRain = 25;
      export const curlyWind = 26;
      export const wind = 27;
      export const rain = 28;
      export const star = 29;
      export const littleRedHeart = 30;
      export const littlePinkHeart = 31;
      export const daisy = 32;
      export const bell = 33;
      export const egg = 34;
      export const projection = 35;
      export const mouseTeleportation = 36;
      export const shamanTeleportation = 37;
      export const lollipopConfetti = 38;
      export const yellowCandyConfetti = 39;
      export const pinkCandyConfetti = 40;
    }
    export namespace shamanObject {
      export const arrow = 0;
      export const littleBox = 1;
      export const box = 2;
      export const littleBoard = 3;
      export const board = 4;
      export const ball = 6;
      export const trampoline = 7;
      export const anvil = 10;
      export const cannon = 17;
      export const bomb = 23;
      export const orangePortal = 26;
      export const blueBalloon = 28;
      export const redBalloon = 29;
      export const greenBalloon = 30;
      export const yellowBalloon = 31;
      export const rune = 32;
      export const chicken = 33;
      export const snowBall = 34;
      export const cupidonArrow = 35;
      export const apple = 39;
      export const sheep = 40;
      export const littleBoardIce = 45;
      export const littleBoardChocolate = 46;
      export const iceCube = 54;
      export const cloud = 57;
      export const bubble = 59;
      export const tinyBoard = 60;
      export const companionCube = 61;
      export const stableRune = 62;
      export const balloonFish = 65;
      export const longBoard = 67;
      export const triangle = 68;
      export const sBoard = 69;
      export const paperPlane = 80;
      export const rock = 85;
      export const pumpkinBall = 89;
      export const tombstone = 90;
      export const paperBall = 95;
    }
  }
  export { $enum as enum }
  export namespace Enums {
    export const enum BonusType {
        point = 0,
        speed = 1,
        death = 2,
        spring = 3,
        booster = 5,
        electricArc = 6,
    }
    export const enum EmoteType {
        dance = 0,
        laugh = 1,
        cry = 2,
        kiss = 3,
        angry = 4,
        clap = 5,
        sleep = 6,
        facepaw = 7,
        sit = 8,
        confetti = 9,
        flag = 10,
        marshmallow = 11,
        selfie = 12,
        highfive = 13,
        partyhorn = 16,
        hug = 17,
        jigglypuff = 20,
        kissing = 21,
        carnaval = 24,
        rockpaperscissors = 25,
    }
    export const enum GroundType {
        wood = 0,
        ice = 1,
        trampoline = 2,
        lava = 3,
        chocolate = 4,
        earth = 5,
        grass = 6,
        sand = 7,
        cloud = 8,
        water = 9,
        stone = 10,
        snow = 11,
        rectangle = 12,
        circle = 13,
        invisible = 14,
        web = 15,
        yellowGrass = 17,
        pinkGrass = 18,
        acid = 19,
    }
    export const enum ParticleType {
        whiteGlitter = 0,
        blueGlitter = 1,
        orangeGlitter = 2,
        cloud = 3,
        dullWhiteGlitter = 4,
        heart = 5,
        bubble = 6,
        tealGlitter = 9,
        spirit = 10,
        yellowGlitter = 11,
        ghostSpirit = 12,
        redGlitter = 13,
        waterBubble = 14,
        plus1 = 15,
        plus10 = 16,
        plus12 = 17,
        plus14 = 18,
        plus16 = 19,
        meep = 20,
        redConfetti = 21,
        greenConfetti = 22,
        blueConfetti = 23,
        yellowConfetti = 24,
        diagonalRain = 25,
        curlyWind = 26,
        wind = 27,
        rain = 28,
        star = 29,
        littleRedHeart = 30,
        littlePinkHeart = 31,
        daisy = 32,
        bell = 33,
        egg = 34,
        projection = 35,
        mouseTeleportation = 36,
        shamanTeleportation = 37,
        lollipopConfetti = 38,
        yellowCandyConfetti = 39,
        pinkCandyConfetti = 40,
    }
    export const enum ShamanObjectType {
        arrow = 0,
        littleBox = 1,
        box = 2,
        littleBoard = 3,
        board = 4,
        ball = 6,
        trampoline = 7,
        anvil = 10,
        cannon = 17,
        bomb = 23,
        orangePortal = 26,
        blueBalloon = 28,
        redBalloon = 29,
        greenBalloon = 30,
        yellowBalloon = 31,
        rune = 32,
        chicken = 33,
        snowBall = 34,
        cupidonArrow = 35,
        apple = 39,
        sheep = 40,
        littleBoardIce = 45,
        littleBoardChocolate = 46,
        iceCube = 54,
        cloud = 57,
        bubble = 59,
        tinyBoard = 60,
        companionCube = 61,
        stableRune = 62,
        balloonFish = 65,
        longBoard = 67,
        triangle = 68,
        sBoard = 69,
        paperPlane = 80,
        rock = 85,
        pumpkinBall = 89,
        tombstone = 90,
        paperBall = 95,
    }
  }
}
