// !! This file is generated by an NPM script. !!

declare namespace tfm {
  namespace $enum {
    namespace bonus {
      const point = 0;
      const speed = 1;
      const death = 2;
      const spring = 3;
      const booster = 5;
      const electricArc = 6;
    }

    namespace emote {
      const dance = 0;
      const laugh = 1;
      const cry = 2;
      const kiss = 3;
      const angry = 4;
      const clap = 5;
      const sleep = 6;
      const facepaw = 7;
      const sit = 8;
      const confetti = 9;
      const flag = 10;
      const marshmallow = 11;
      const selfie = 12;
      const highfive = 13;
      const partyhorn = 16;
      const hug = 17;
      const jigglypuff = 20;
      const kissing = 21;
      const carnaval = 24;
      const rockpaperscissors = 25;
    }

    namespace ground {
      const wood = 0;
      const ice = 1;
      const trampoline = 2;
      const lava = 3;
      const chocolate = 4;
      const earth = 5;
      const grass = 6;
      const sand = 7;
      const cloud = 8;
      const water = 9;
      const stone = 10;
      const snow = 11;
      const rectangle = 12;
      const circle = 13;
      const invisible = 14;
      const web = 15;
      const yellowGrass = 17;
      const pinkGrass = 18;
      const acid = 19;
    }

    namespace particle {
      const whiteGlitter = 0;
      const blueGlitter = 1;
      const orangeGlitter = 2;
      const cloud = 3;
      const dullWhiteGlitter = 4;
      const heart = 5;
      const bubble = 6;
      const tealGlitter = 9;
      const spirit = 10;
      const yellowGlitter = 11;
      const ghostSpirit = 12;
      const redGlitter = 13;
      const waterBubble = 14;
      const plus1 = 15;
      const plus10 = 16;
      const plus12 = 17;
      const plus14 = 18;
      const plus16 = 19;
      const meep = 20;
      const redConfetti = 21;
      const greenConfetti = 22;
      const blueConfetti = 23;
      const yellowConfetti = 24;
      const diagonalRain = 25;
      const curlyWind = 26;
      const wind = 27;
      const rain = 28;
      const star = 29;
      const littleRedHeart = 30;
      const littlePinkHeart = 31;
      const daisy = 32;
      const bell = 33;
      const egg = 34;
      const projection = 35;
      const mouseTeleportation = 36;
      const shamanTeleportation = 37;
      const lollipopConfetti = 38;
      const yellowCandyConfetti = 39;
      const pinkCandyConfetti = 40;
    }

    namespace shamanObject {
      const arrow = 0;
      const littleBox = 1;
      const box = 2;
      const littleBoard = 3;
      const board = 4;
      const ball = 6;
      const trampoline = 7;
      const anvil = 10;
      const cannon = 17;
      const bomb = 23;
      const orangePortal = 26;
      const blueBalloon = 28;
      const redBalloon = 29;
      const greenBalloon = 30;
      const yellowBalloon = 31;
      const rune = 32;
      const chicken = 33;
      const snowBall = 34;
      const cupidonArrow = 35;
      const apple = 39;
      const sheep = 40;
      const littleBoardIce = 45;
      const littleBoardChocolate = 46;
      const iceCube = 54;
      const cloud = 57;
      const bubble = 59;
      const tinyBoard = 60;
      const companionCube = 61;
      const stableRune = 62;
      const balloonFish = 65;
      const longBoard = 67;
      const triangle = 68;
      const sBoard = 69;
      const paperPlane = 80;
      const rock = 85;
      const pumpkinBall = 89;
      const tombstone = 90;
      const paperBall = 95;
    }

  }

  export { $enum as enum }
}
