// !! This file is generated by an NPM script. !!

declare namespace tfm {
  namespace $enum {
    namespace bonus {
      const point = 0;
      const speed = 1;
      const death = 2;
      const spring = 3;
      const booster = 5;
      const electricArc = 6;
    }

    const enum BonusType {
      point = 0,
      speed = 1,
      death = 2,
      spring = 3,
      booster = 5,
      electricArc = 6,
    }

    namespace emote {
      const dance = 0;
      const laugh = 1;
      const cry = 2;
      const kiss = 3;
      const angry = 4;
      const clap = 5;
      const sleep = 6;
      const facepaw = 7;
      const sit = 8;
      const confetti = 9;
      const flag = 10;
      const marshmallow = 11;
      const selfie = 12;
      const highfive = 13;
      const partyhorn = 16;
      const hug = 17;
      const jigglypuff = 20;
      const kissing = 21;
      const carnaval = 24;
      const rockpaperscissors = 25;
    }

    const enum EmoteType {
      dance = 0,
      laugh = 1,
      cry = 2,
      kiss = 3,
      angry = 4,
      clap = 5,
      sleep = 6,
      facepaw = 7,
      sit = 8,
      confetti = 9,
      flag = 10,
      marshmallow = 11,
      selfie = 12,
      highfive = 13,
      partyhorn = 16,
      hug = 17,
      jigglypuff = 20,
      kissing = 21,
      carnaval = 24,
      rockpaperscissors = 25,
    }

    namespace ground {
      const wood = 0;
      const ice = 1;
      const trampoline = 2;
      const lava = 3;
      const chocolate = 4;
      const earth = 5;
      const grass = 6;
      const sand = 7;
      const cloud = 8;
      const water = 9;
      const stone = 10;
      const snow = 11;
      const rectangle = 12;
      const circle = 13;
      const invisible = 14;
      const web = 15;
      const yellowGrass = 17;
      const pinkGrass = 18;
      const acid = 19;
    }

    const enum GroundType {
      wood = 0,
      ice = 1,
      trampoline = 2,
      lava = 3,
      chocolate = 4,
      earth = 5,
      grass = 6,
      sand = 7,
      cloud = 8,
      water = 9,
      stone = 10,
      snow = 11,
      rectangle = 12,
      circle = 13,
      invisible = 14,
      web = 15,
      yellowGrass = 17,
      pinkGrass = 18,
      acid = 19,
    }

    namespace particle {
      const whiteGlitter = 0;
      const blueGlitter = 1;
      const orangeGlitter = 2;
      const cloud = 3;
      const dullWhiteGlitter = 4;
      const heart = 5;
      const bubble = 6;
      const tealGlitter = 9;
      const spirit = 10;
      const yellowGlitter = 11;
      const ghostSpirit = 12;
      const redGlitter = 13;
      const waterBubble = 14;
      const plus1 = 15;
      const plus10 = 16;
      const plus12 = 17;
      const plus14 = 18;
      const plus16 = 19;
      const meep = 20;
      const redConfetti = 21;
      const greenConfetti = 22;
      const blueConfetti = 23;
      const yellowConfetti = 24;
      const diagonalRain = 25;
      const curlyWind = 26;
      const wind = 27;
      const rain = 28;
      const star = 29;
      const littleRedHeart = 30;
      const littlePinkHeart = 31;
      const daisy = 32;
      const bell = 33;
      const egg = 34;
      const projection = 35;
      const mouseTeleportation = 36;
      const shamanTeleportation = 37;
      const lollipopConfetti = 38;
      const yellowCandyConfetti = 39;
      const pinkCandyConfetti = 40;
    }

    const enum ParticleType {
      whiteGlitter = 0,
      blueGlitter = 1,
      orangeGlitter = 2,
      cloud = 3,
      dullWhiteGlitter = 4,
      heart = 5,
      bubble = 6,
      tealGlitter = 9,
      spirit = 10,
      yellowGlitter = 11,
      ghostSpirit = 12,
      redGlitter = 13,
      waterBubble = 14,
      plus1 = 15,
      plus10 = 16,
      plus12 = 17,
      plus14 = 18,
      plus16 = 19,
      meep = 20,
      redConfetti = 21,
      greenConfetti = 22,
      blueConfetti = 23,
      yellowConfetti = 24,
      diagonalRain = 25,
      curlyWind = 26,
      wind = 27,
      rain = 28,
      star = 29,
      littleRedHeart = 30,
      littlePinkHeart = 31,
      daisy = 32,
      bell = 33,
      egg = 34,
      projection = 35,
      mouseTeleportation = 36,
      shamanTeleportation = 37,
      lollipopConfetti = 38,
      yellowCandyConfetti = 39,
      pinkCandyConfetti = 40,
    }

    namespace shamanObject {
      const arrow = 0;
      const littleBox = 1;
      const box = 2;
      const littleBoard = 3;
      const board = 4;
      const ball = 6;
      const trampoline = 7;
      const anvil = 10;
      const cannon = 17;
      const bomb = 23;
      const orangePortal = 26;
      const blueBalloon = 28;
      const redBalloon = 29;
      const greenBalloon = 30;
      const yellowBalloon = 31;
      const rune = 32;
      const chicken = 33;
      const snowBall = 34;
      const cupidonArrow = 35;
      const apple = 39;
      const sheep = 40;
      const littleBoardIce = 45;
      const littleBoardChocolate = 46;
      const iceCube = 54;
      const cloud = 57;
      const bubble = 59;
      const tinyBoard = 60;
      const companionCube = 61;
      const stableRune = 62;
      const balloonFish = 65;
      const longBoard = 67;
      const triangle = 68;
      const sBoard = 69;
      const paperPlane = 80;
      const rock = 85;
      const pumpkinBall = 89;
      const tombstone = 90;
      const paperBall = 95;
    }

    const enum ShamanObjectType {
      arrow = 0,
      littleBox = 1,
      box = 2,
      littleBoard = 3,
      board = 4,
      ball = 6,
      trampoline = 7,
      anvil = 10,
      cannon = 17,
      bomb = 23,
      orangePortal = 26,
      blueBalloon = 28,
      redBalloon = 29,
      greenBalloon = 30,
      yellowBalloon = 31,
      rune = 32,
      chicken = 33,
      snowBall = 34,
      cupidonArrow = 35,
      apple = 39,
      sheep = 40,
      littleBoardIce = 45,
      littleBoardChocolate = 46,
      iceCube = 54,
      cloud = 57,
      bubble = 59,
      tinyBoard = 60,
      companionCube = 61,
      stableRune = 62,
      balloonFish = 65,
      longBoard = 67,
      triangle = 68,
      sBoard = 69,
      paperPlane = 80,
      rock = 85,
      pumpkinBall = 89,
      tombstone = 90,
      paperBall = 95,
    }

  }

  export { $enum as enum }
}
